### ISSUE TITLE
Errore nel testo allarmi esportato

### ISSUE THREAD

**Issue by bribri96** [Parozzz/TiaAddIn-Spin#3]
Quando viene utilizzata la funzione anti-slip e nel testo allarme viene inserito {alarm_num} non viene gestito correttamente il numero dell'allarme
![image](https://github.com/user-attachments/assets/9519dba9-4d0b-4e1a-8269-e3fc28d51873)
![image](https://github.com/user-attachments/assets/a37886d1-35d2-487a-a42b-9476ca290b13)

**Comment by Parozzz** [comment]
This seems to be already fixed with #5
